import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    // alignItems: 'center',
  },

  containerheader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#063852',
    width: 360,
    height: 40,
  },
  imgback: {
    width: 20,
    height: 20,
    marginLeft: 10,
  },
  img: {
    width: 120,
    height: 120,
    borderRadius: 20,
    marginTop: 20,
    // marginLeft: 90,
  },
  container2: {flex:1,alignItems:'center'},
  txtproduct: {
    fontSize: 20,
    fontWeight: 'bold',
    marginRight: 225,
    color: '#fff',
    marginTop: 40,
    textShadowColor: 'black',
    textShadowRadius: 0.5,
    textShadowOffset: {
      width: 1,
      height: 1,
    },
  },
  inputproduct: {
    width: 300,
    height: 40,
    backgroundColor: '#fff',
    marginTop: 10,
    borderRadius: 10,
  },
  viewpricestock: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    // width: 200,
  },
  txtprice: {
    fontSize: 20,
    fontWeight: 'bold',
    // marginRight: 225,
    color: '#fff',
    marginTop: 10,
    textShadowColor: 'black',
    textShadowRadius: 0.5,
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    right: 95,
  },
  txtstock: {
    fontSize: 20,
    fontWeight: 'bold',
    // marginRight: 225,
    color: '#fff',
    marginTop: 10,
    textShadowColor: 'black',
    textShadowRadius: 0.5,
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    left: 70,
  },
  viewinputpricestock: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 300,
    marginTop: 10,
  },
  inputprice: {
    width: 180,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  inputstock: {
    width: 80,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  viewcategorydiscount: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtcategory: {
    fontSize: 20,
    fontWeight: 'bold',
    // marginRight: 225,
    color: '#fff',
    marginTop: 10,
    textShadowColor: 'black',
    textShadowRadius: 0.5,
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    right: 70,
  },
  txtdiscount: {
    fontSize: 20,
    fontWeight: 'bold',
    // marginRight: 225,
    color: '#fff',
    marginTop: 10,
    textShadowColor: 'black',
    textShadowRadius: 0.5,
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    left: 70,
  },
  viewinputcategorydiscount: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 300,
    marginTop: 10,
  },
  viewpicker: {
    width: 180,
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  inputdiscount: {
    width: 80,
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  txtdescription: {
    fontSize: 20,
    fontWeight: 'bold',
    // marginRight: 225,
    color: '#fff',
    marginTop: 10,
    textShadowColor: 'black',
    textShadowRadius: 0.5,
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    right: 100,
  },
  inputdescription: {
    width: 300,
    // height: 150,
    backgroundColor: '#fff',
    borderColor: 'black',
    borderWidth: 2,
    // marginTop:10,
    textAlignVertical: 'top',
    borderRadius: 10,
  },
  touchedit: {
      width:300,
      height:40,
      alignItems:'center',
      justifyContent:"center",
      backgroundColor:'#87CEEB',
      borderRadius:20,
      marginTop:40
  }
});
